services:
  scrna-pipeline:
    build: .
    image: scrna-seq-pipeline:latest
    container_name: scrna_analysis_container
    volumes:
      # Maps your entire project folder (including main.R and scripts/) into the container
      - .:/workspace